[package]
name = "magic"
version = "0.1.0"
authors = ["awygle <awygle@gmail.com>"]
edition = "2018"

[dependencies]
gumdrop = "*"
ux = "*"
itertools = "*"
arraydeque = "*"
magic-macros = {path = "../magic-macros"}
magic-types = {path = "../magic-types"}
serde_json = "*"
enum_derive = "*"
strum = "*"
strum_macros = "*"
